name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: TypeScript Compile Check
      id: typescript-compile-check
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: TypeScript Compile Check
        setup-command: npm install
        command: npm run typecheck
        timeout: 10
        max-score: 1
    - name: Runtime Tests
      id: runtime-tests
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Runtime Tests
        setup-command: npm install
        command: npm test
        timeout: 10
        max-score: 1
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TYPESCRIPT-COMPILE-CHECK_RESULTS: "${{steps.typescript-compile-check.outputs.result}}"
        RUNTIME-TESTS_RESULTS: "${{steps.runtime-tests.outputs.result}}"
      with:
        runners: typescript-compile-check,runtime-tests
